### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by TranzUA** [scottrbailey/WLED-Utils#4]
The firmware is stable, thank you very much! But there is enough memory to control 266 LEDs. Maybe you can simplify the code somewhere? It would be very nice to drive 300 LEDs.

**Comment by scottrbailey** [comment]
I just compiled SR ESP8266 for SP511E, I didn’t write it.  The memory issue is due to the way ESP8266 manages pins and the fact that they used pin 3 as the data pin. If you switch to using pin 1 or 2, it will use less memory. To do that you’ll need to follow divsys’s guide for hacking the hardware on the WLED discourse.

**Comment by TranzUA** [comment]
Share the link for hacking the hardware on the WLED discourse, please

**Comment by scottrbailey** [comment]
https://wled.discourse.group/t/sp511e-upgrade-project/3753
